-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Course"
(
    id integer NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    discreption text,
    credit integer,
    available boolean NOT NULL,
    "courseCode" text NOT NULL,
    name text NOT NULL,
    major text,
    level integer,
    PRIMARY KEY (id)
);

CREATE TABLE public."Enrollment"
(
    id integer NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    "supervisorId" integer,
    "studentID" integer,
    "courseID" integer,
    "isAproved" boolean NOT NULL,
    status text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."FinishedCourses"
(
    "courseId" integer NOT NULL,
    "studentID" integer NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    grade double precision,
    semester "Semester",
    "instructorName" text,
    PRIMARY KEY ("courseId", "studentID")
);

CREATE TABLE public."Student"
(
    id integer NOT NULL,
    "uniCode" text NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    fname character varying(255) NOT NULL,
    lname character varying(255) NOT NULL,
    gender "Gender",
    password text,
    email text NOT NULL,
    level integer,
    semester "Semester",
    major text,
    "creditDone" integer,
    "creditHave" integer,
    "supervisorId" integer,
    "GPA" double precision,
    "lastTermGPA" double precision,
    PRIMARY KEY (id)
);

CREATE TABLE public."Supervisor"
(
    id integer NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    fname character varying(255) NOT NULL,
    lname character varying(255) NOT NULL,
    gender "Gender",
    password text,
    email text NOT NULL,
    phone text,
    PRIMARY KEY (id)
);

CREATE TABLE public."_CoursePrerequisites"
(
    "A" integer NOT NULL,
    "B" integer NOT NULL
);

CREATE TABLE public._prisma_migrations
(
    id character varying(36) NOT NULL,
    checksum character varying(64) NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) NOT NULL,
    logs text,
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone NOT NULL,
    applied_steps_count integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."Enrollment"
    ADD FOREIGN KEY ("courseID")
    REFERENCES public."Course" (id)
    NOT VALID;


ALTER TABLE public."Enrollment"
    ADD FOREIGN KEY ("studentID")
    REFERENCES public."Student" (id)
    NOT VALID;


ALTER TABLE public."Enrollment"
    ADD FOREIGN KEY ("supervisorId")
    REFERENCES public."Supervisor" (id)
    NOT VALID;


ALTER TABLE public."FinishedCourses"
    ADD FOREIGN KEY ("courseId")
    REFERENCES public."Course" (id)
    NOT VALID;


ALTER TABLE public."FinishedCourses"
    ADD FOREIGN KEY ("studentID")
    REFERENCES public."Student" (id)
    NOT VALID;


ALTER TABLE public."Student"
    ADD FOREIGN KEY ("supervisorId")
    REFERENCES public."Supervisor" (id)
    NOT VALID;


ALTER TABLE public."_CoursePrerequisites"
    ADD FOREIGN KEY ("A")
    REFERENCES public."Course" (id)
    NOT VALID;


ALTER TABLE public."_CoursePrerequisites"
    ADD FOREIGN KEY ("B")
    REFERENCES public."Course" (id)
    NOT VALID;

END;