pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    
    stages {
        stage('database') {
            agent {
        docker {
            image 'postgres'
            args '-e POSTGRES_USER=docker -e POSTGRES_PASSWORD=docker -e POSTGRES_DB=docker library/postgres'
                }
    }
        }
    }
}
