pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    
    stages {
        stage('database') {
            agent {
        docker {
            image 'postgres'
            args '-p 5432:5432'
            reuseNode true

        }
    }
            steps {
                sh ' psql -U postgres -c \"CREATE DATABASE myDatabase WITH ENCODING \"UTF8\" ;\" '
            }
        }
       
       
    }
}
